### PR TITLE
[FIX] #2625 #2567 #2495 #2494

### PR DESCRIPTION
**Pull request by KKamaa**
So in this I added the Therp requests. The only known issue is about the pause button, in the library documentation [angular-timer](https://github.com/siddii/angular-timer) you will notice under issues several people have raised the concern of the pause time does not start from where the timer was started, seems to start from a continuous point. I tried a [fix](https://github.com/siddii/angular-timer/commit/338b665ed5d369605b2fb1a8be096654b4b97fbb) for it directly on the library but does not seem to work. I might need some insight in this. Otherwise a [sample](https://streamable.com/i8q3eq) tested in Opera mini, so Chrome,Firefox,Opera mini.

### CODE REVIEW

**Comment by KKamaa** [comment]
sample tested in Opera mini, so Chrome,Firefox,Opera mini

https://user-images.githubusercontent.com/10249832/154246717-2e25d81e-855b-46fb-968c-c41fe5fe000d.mp4

**Comment by KKamaa** [comment]
re-installing timer package in browser might be required to fully support the new fixes and features.

**Comment by thomaspaulb** [comment]
@KKamaa Regarding the stop/start issue - I see the latest "master" branch of angular-timer includes this fix:

https://github.com/siddii/angular-timer/pull/331

Maybe it fixes the problem you are describing ?

**Comment by KKamaa** [comment]
> @KKamaa Regarding the stop/start issue - I see the latest "master" branch of angular-timer includes this fix:
> 
> [siddii/angular-timer#331](https://github.com/siddii/angular-timer/pull/331)
> 
> Maybe it fixes the problem you are describing ?

@thomaspaulb tried it doesn't seem to work

**Review by gjotten — APPROVED** [review]

**Comment by KKamaa** [comment]
> @KKamaa You committed a huge `node_modules` folder, so now the PR contains 9000 changed files.
> 
> If you don't have a good reasoning behind that, please revert it....

reverted though that was strange :(

**Comment by thomaspaulb** [comment]
@KKamaa Running `npm install some_nodejs_module` will default to installing it in `./node_modules`, so wherever you're currently at... maybe that was the reason

**Review by thomaspaulb — APPROVED** [review]

**Comment by KKamaa** [comment]
Ah yes true was trying to package the extension using a node tool. Should have checked or add it to gitignore

**Pull request merged**
